# -*- coding: utf-8 -*-
"""Generate report_fonts.css with base64-embedded Pyidaungsu fonts for wkhtmltopdf."""
import base64
import os

FONTS_DIR = os.path.join(os.path.dirname(__file__), 'static', 'src', 'fonts')
CSS_DIR = os.path.join(os.path.dirname(__file__), 'static', 'src', 'css')

REGULAR_TTF = os.path.join(FONTS_DIR, 'Pyidaungsu-2.5.3_Regular.ttf')
BOLD_TTF = os.path.join(FONTS_DIR, 'Pyidaungsu-2.5.3_Bold.ttf')
OUTPUT_CSS = os.path.join(CSS_DIR, 'report_fonts.css')


def encode_font(path):
    with open(path, 'rb') as f:
        return base64.b64encode(f.read()).decode('ascii')


def main():
    print(f"Encoding {REGULAR_TTF}...")
    regular_b64 = encode_font(REGULAR_TTF)
    print(f"Encoding {BOLD_TTF}...")
    bold_b64 = encode_font(BOLD_TTF)

    css = f"""/* Pyidaungsu fonts embedded as base64 for wkhtmltopdf PDF rendering.
   Generated by generate_font_css.py - DO NOT EDIT MANUALLY */
@font-face {{
    font-family: 'Pyidaungsu';
    src: url('data:font/truetype;base64,{regular_b64}') format('truetype');
    font-weight: normal;
    font-style: normal;
}}

@font-face {{
    font-family: 'Pyidaungsu';
    src: url('data:font/truetype;base64,{bold_b64}') format('truetype');
    font-weight: bold;
    font-style: normal;
}}

/* Apply Pyidaungsu to all report elements */
body,
body.o_body_pdf,
.page,
table,
td,
th,
div,
span,
p,
h1,
h2,
h3,
h4,
h5,
h6,
address,
strong,
b,
i,
em,
small,
.o_report_layout,
.article,
.hongsar-report-wrap,
.hongsar-report-wrap table,
.hongsar-report-wrap td,
.hongsar-report-wrap th,
.hongsar-report-wrap div,
.hongsar-report-wrap span,
.hongsar-report-wrap p,
.hongsar-report-wrap h1,
.hongsar-report-wrap h2,
.hongsar-report-wrap .formal-report-page,
.hongsar-report-wrap .formal-report-page * {{
    font-family: 'Noto Sans Myanmar', 'Pyidaungsu', 'Padauk', sans-serif !important;
    font-size: 16px !important;
    line-height: 1.45 !important;
}}

.hongsar-invoice-wrap,
.hongsar-invoice-wrap table,
.hongsar-invoice-wrap td,
.hongsar-invoice-wrap th,
.hongsar-invoice-wrap div,
.hongsar-invoice-wrap span,
.hongsar-invoice-wrap p,
.hongsar-invoice-wrap * {{
    font-family: 'Noto Sans Myanmar', 'Pyidaungsu', 'Padauk', sans-serif !important;
    font-size: 14px !important;
    line-height: 1.4 !important;
}}

strong,
b,
th,
h1,
h2,
h3,
h4,
h5,
h6 {{
    font-weight: bold;
}}
"""

    print(f"Writing {OUTPUT_CSS}...")
    with open(OUTPUT_CSS, 'w', encoding='utf-8') as f:
        f.write(css)
    
    print(f"Done! CSS file size: {os.path.getsize(OUTPUT_CSS) / 1024:.1f} KB")


if __name__ == '__main__':
    main()
