# -*- coding: utf-8 -*-
"""Generate org_reports_fix.css with base64-embedded Pyidaungsu fonts for wkhtmltopdf."""
import base64
import os

# Use font files from hongsar_reports module (they are the same fonts)
HONGSAR_REPORTS_FONTS = os.path.join(
    os.path.dirname(os.path.dirname(__file__)), 
    'hongsar_reports', 'static', 'src', 'fonts'
)
CSS_DIR = os.path.join(os.path.dirname(__file__), 'static', 'src', 'css')

REGULAR_TTF = os.path.join(HONGSAR_REPORTS_FONTS, 'Pyidaungsu-2.5.3_Regular.ttf')
BOLD_TTF = os.path.join(HONGSAR_REPORTS_FONTS, 'Pyidaungsu-2.5.3_Bold.ttf')
OUTPUT_CSS = os.path.join(CSS_DIR, 'org_reports_fix.css')


def encode_font(path):
    with open(path, 'rb') as f:
        return base64.b64encode(f.read()).decode('ascii')


def main():
    print(f"Encoding {REGULAR_TTF}...")
    regular_b64 = encode_font(REGULAR_TTF)
    print(f"Encoding {BOLD_TTF}...")
    bold_b64 = encode_font(BOLD_TTF)

    css = f"""/* Pyidaungsu fonts embedded as base64 for wkhtmltopdf PDF rendering.
   Generated by generate_font_css.py - DO NOT EDIT MANUALLY */
@font-face {{
    font-family: 'Pyidaungsu';
    src: url('data:font/truetype;base64,{regular_b64}') format('truetype');
    font-weight: normal;
    font-style: normal;
}}

@font-face {{
    font-family: 'Pyidaungsu';
    src: url('data:font/truetype;base64,{bold_b64}') format('truetype');
    font-weight: bold;
    font-style: normal;
}}

/* Myanmar font for all report output (PDF + HTML preview) */
body,
.page,
table,
td,
th,
div,
span,
p,
h1,
h2,
h3,
h4,
h5,
h6,
address,
strong,
b,
i,
em,
small,
.o_report_layout,
.article {{
    font-family: 'Pyidaungsu', 'Pyidaungsu Regular', 'Noto Sans Myanmar', 'Padauk', sans-serif !important;
}}

strong,
b,
h1,
h2,
h3,
h4,
h5,
h6 {{
    font-weight: bold;
}}

/* Sale order lines: narrow unit price, clip long amounts */
table.o_main_table th[name='th_priceunit'],
table.o_main_table td[name='td_priceunit'] {{
    width: 52px !important;
    max-width: 52px !important;
    min-width: 52px !important;
    overflow: hidden !important;
    text-overflow: ellipsis !important;
    white-space: nowrap !important;
    padding-left: 2px !important;
    padding-right: 2px !important;
    font-size: 0.9em;
}}

table.o_main_table td[name='td_priceunit'] > span {{
    display: block;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}}
"""

    print(f"Writing {OUTPUT_CSS}...")
    os.makedirs(CSS_DIR, exist_ok=True)
    with open(OUTPUT_CSS, 'w', encoding='utf-8') as f:
        f.write(css)
    
    print(f"Done! CSS file size: {os.path.getsize(OUTPUT_CSS) / 1024:.1f} KB")


if __name__ == '__main__':
    main()
